/* eslint-disable global-require */
export const address = require('./address');
export const availability = require('./availability');
export const close = require('./close');
export const pickup = require('./pickup');
export const rates = require('./rates');
export const shipmentDelete = require('./shipment/delete');
export const shipmentLTLFreight = require('./shipment/ltl-freight');
export const shipmentMultiPackage = require('./shipment/multi-package');
export const shipmentStandard = require('./shipment/standard');
export const shipmentWithCOD = require('./shipment/standard-with-cod');
export const trackingExpressGroundArrivedAtFedex = require('./tracking/express-ground-arrived-at-fedex');
export const trackingExpressGroundArrivedAtSortFacility = require('./tracking/express-ground-at-sort-facility');
export const trackingExpressGroundDelivered = require('./tracking/express-ground-delivered');
export const trackingExpressGroundDepartedFedex = require('./tracking/express-ground-departed-fedex');
export const trackingExpressGroundOnVehicleForDelivery = require('./tracking/express-ground-on-vehicle-for-delivery'); //
export const trackingExpressGroundPickedUp = require('./tracking/express-ground-picked-up'); //
export const trackingExpressGroundSentToFedex = require('./tracking/express-ground-sent-to-fedex');
export const trackingExpressGroundTendered = require('./tracking/express-ground-tendered');
